name: Build and Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - test2
jobs:
  build:
    name: Build
    uses: Logius-standaarden/Automatisering/.github/workflows/build.yml@main
